<a href="https://colab.research.google.com/github/masanchezpa/AlgorithmsUN2024-I/blob/main/Lab5/masanchezpa_Lab5_Group18Partitions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Partitions**

## **Names:** David Felipe Marin Rosas, Jesús Ernesto Quiñones Cely, Maria Camila Sanchez Paez.
## **UN Ids:** dmarinro, jequinonesc, masanchezpa.
## **List numbers:** 18, 23, 28.
## **Group :** 18.

_If you use an existing codes include the reference, link and a explanation of how the code works._

## 1. Write a code that produces the Bell numbers that count the possible partitions of a set for $n$ elements.

**Hints**:
-  Output the n-th Bell Number - [stackexchange](https://codegolf.stackexchange.com/questions/132379/output-the-n-th-bell-number).

- Bell number [wikipedia](https://en.wikipedia.org/wiki/Bell_number)






In [ ]:
import numpy as np

def bell(n):
  b = 1

  # Create a table to store Bell numbers, with numpy so its super efficient
  bell_table = np.zeros((n+1, n+1), dtype=int)

  # Base case, top of the lower triangle
  bell_table[0][0] = b

  # Fill the table using the Peirce triangle
  for i in range(1, n + 1):
    bell_table[i][0] = bell_table[i - 1][i - 1]
    for j in range(1, i + 1):
      bell_table[i][j] = bell_table[i - 1][j - 1] + bell_table[i][j - 1]

  # The first entry of the n row in the table is the Bell number for n
  b = bell_table[n][0]
  print(bell_table)

  # Nice, we did it
  return b

In [ ]:
# Usage example
n = 5
result = bell(n)
print(f"The Bell number for {n} is {result}")

[[  1   0   0   0   0   0]
 [  1   2   0   0   0   0]
 [  2   3   5   0   0   0]
 [  5   7  10  15   0   0]
 [ 15  20  27  37  52   0]
 [ 52  67  87 114 151 203]]
The Bell number for 5 is 52


## 2.Write a code that that produces the list of all partititions of the set of $[n]=\{ 1,2,3,4 \cdots , n-1, n\}$ with $0 \le n \le 10$.

**Hints**:
- Set partitions in Python - https://stackoverflow.com/questions/19368375/set-partitions-in-python
- Generate all partition of a set - https://www.geeksforgeeks.org/generate-all-partition-of-a-set/

In [ ]:
# Asumes that all elements in the collection are different
def partitionsThisSet(collection):
    # If the collection only contains one element, then there is only one partition
    if len(collection) == 1:
      yield [collection]
      return

    # Otherwise, if the collection has more than one element
    # Get the first element
    first = collection[0]
    # You need to get the first element in all the possible partitions from the first element henceforth (n-1 elements, subset)
    for smaller in partitionsThisSet(collection[1:]):
      # For each partition iterate over the subsets inserting the first at the subset in each position
      for p, subset in enumerate(smaller):
        yield smaller[:p] + [ [first] + subset] + smaller[p+1:]
      # Now that you put it in each subset of smaller
      # Insert it besides smaller, being it a partition of collections too
      yield [ [first] ] + smaller


def partitions(n):
  if n == 0:
    return [[]]
  listNumTillN = list(range(1,n+1))
  result = list(partitionsThisSet(listNumTillN))
  # your code goes here
  return result

In [ ]:
# Usage
# N till which you want to do it, cannot be BIG or colab crashes
N = 7
# Producing all the partitions of the set that goes from 1 till n, using n from 0 up to 10
for n in range(0, N+1):
  print()
  print(f"All possible partitions of the set [n] up till n = {n} are:")
  print()
  for p in partitions(n):
    print(p)
  print()
  print("-------------------------------------------------------")


All possible partitions of the set [n] up till n = 0 are:

[]

-------------------------------------------------------

All possible partitions of the set [n] up till n = 1 are:

[[1]]

-------------------------------------------------------

All possible partitions of the set [n] up till n = 2 are:

[[1, 2]]
[[1], [2]]

-------------------------------------------------------

All possible partitions of the set [n] up till n = 3 are:

[[1, 2, 3]]
[[1], [2, 3]]
[[1, 2], [3]]
[[2], [1, 3]]
[[1], [2], [3]]

-------------------------------------------------------

All possible partitions of the set [n] up till n = 4 are:

[[1, 2, 3, 4]]
[[1], [2, 3, 4]]
[[1, 2], [3, 4]]
[[2], [1, 3, 4]]
[[1], [2], [3, 4]]
[[1, 2, 3], [4]]
[[2, 3], [1, 4]]
[[1], [2, 3], [4]]
[[1, 3], [2, 4]]
[[3], [1, 2, 4]]
[[1], [3], [2, 4]]
[[1, 2], [3], [4]]
[[2], [1, 3], [4]]
[[2], [3], [1, 4]]
[[1], [2], [3], [4]]

-------------------------------------------------------

All possible partitions of the set [n] up till

## 3. Write a code that produces the list of all partititions of the set of $[n]=\{ 1,2,3,4\cdots , n-1, n\}$ with $0 \le n \le 10$ and then with this the sum of elements of each subset for each partition, the sum of this subset should always be the constant: $\frac{n(n+1)}{2}$.

In [ ]:
def partitions_sum(n):
  result = []

  # For each partition get the sums of its subsets
  for partition in partitions(n):

    # Current group of sums for this partition
    currGroupSums = []
    # Summing each subset
    for subset in partition:

      currGroupSums.append(sum(subset))

    # Append the current group of sums to the result
    result.append(currGroupSums)

  # return the result
  return result

In [ ]:
# Usage
# N till which you want to do it, cannot be BIG or colab crashes
N = 7
# Producing all the partitions of the set that goes from 1 till n, using n from 0 up to 10
for n in range(0, N+1):
  print()
  print(f"All possible ways to sum the numbers up till n = {n} are:")
  print()
  for p in partitions_sum(n):
    print(p)
  print()
  print("-------------------------------------------------------")


All possible ways to sum the numbers up till n = 0 are:

[]

-------------------------------------------------------

All possible ways to sum the numbers up till n = 1 are:

[1]

-------------------------------------------------------

All possible ways to sum the numbers up till n = 2 are:

[3]
[1, 2]

-------------------------------------------------------

All possible ways to sum the numbers up till n = 3 are:

[6]
[1, 5]
[3, 3]
[2, 4]
[1, 2, 3]

-------------------------------------------------------

All possible ways to sum the numbers up till n = 4 are:

[10]
[1, 9]
[3, 7]
[2, 8]
[1, 2, 7]
[6, 4]
[5, 5]
[1, 5, 4]
[4, 6]
[3, 7]
[1, 3, 6]
[3, 3, 4]
[2, 4, 4]
[2, 3, 5]
[1, 2, 3, 4]

-------------------------------------------------------

All possible ways to sum the numbers up till n = 5 are:

[15]
[1, 14]
[3, 12]
[2, 13]
[1, 2, 12]
[6, 9]
[5, 10]
[1, 5, 9]
[4, 11]
[3, 12]
[1, 3, 11]
[3, 3, 9]
[2, 4, 9]
[2, 3, 10]
[1, 2, 3, 9]
[10, 5]
[9, 6]
[1, 9, 5]
[8, 7]
[7, 8]
[1, 7, 7]
[3